# An example pipeline to be compiled for execution using UPMEM

[pipeline]
name = "filer_multiples"
globals = [
    { name = "factor", type = "uint32_t" }
]

[[stages]]
kind = "input"
inputs = ["uint64_t"]

[[stages]]
# filters data elements by a predicate
kind = "filter"
program = """
return *in_ptr % factor == 0;
""" 
