# An example pipeline to be compiled for execution using UPMEM

[pipeline]
name = "scale_by"
globals = [
    { name = "scale", type = "uint64_t" }
]

[[stages]]
kind = "input"
inputs = ["uint64_t"]

[[stages]]
kind = "map"
output = "uint64_t"
program = """
*out_ptr = *in_ptr * scale;
"""
