[pipeline]
name = "matmul"
globals = [
    { name = "input_vec", type = "uint64_t[100]" }
]

[[stages]]
kind = "input"
inputs = ["uint64_t[100]"]

[[stages]]
# filters data elements by a predicate
kind = "map"
output = "uint64_t"
program = """
uint64_t acc = 0;
for (int i = 0; i < 100; ++i) {
    acc += (*in_ptr)[i] * input_vec[i];
}
*out_ptr = acc;
""" 
