# An example pipeline to be compiled for execution using UPMEM

[pipeline]
name = "sum_reduce"
constants = [
    { name = "zero", type = "uint32_t", init = "0" },
]

[[stages]]
kind = "input"
inputs = ["uint32_t"]

[[stages]]
kind = "reduce"
identity = "zero"
output = "uint32_t"
program = """
*out_ptr += *in_ptr;
"""
combine = """
*out_ptr += *in_ptr;
"""