# An example pipeline to be compiled for execution using UPMEM

[pipeline]
name = "vector_add"
globals = []
constants = []

[[stages]]
kind = "input"
inputs = [
    "uint64_t",
    "uint64_t"
]
output = "uint64_t[2]"
program = """
(*out_ptr)[0] = *in_ptr_0;
(*out_ptr)[1] = *in_ptr_1;
"""

[[stages]]
kind = "map"
output = "uint64_t"
program = """
*out_ptr = (*in_ptr)[0] + (*in_ptr)[1];
"""