add_rules("mode.debug", "mode.release")

toolchain("upmem-clang")
	set_sdkdir("/usr/local/upmem")
	set_toolset("cc", "dpu-upmem-dpurte-clang")
	set_toolset("ld", "dpu-upmem-dpurte-clang")
	set_toolset("sh", "dpu-upmem-dpurte-clang")
	set_toolset("mm", "dpu-upmem-dpurte-clang")
	set_toolset("as", "dpu-upmem-dpurte-clang")
    -- set_toolset("cxx", "clang", "clang++")
    -- set_toolset("ar", "ar")
    -- set_toolset("ex", "ar")
    -- set_toolset("strip", "strip")
    -- set_toolset("mxx", "clang", "clang++")
	add_cflags("-DNR_TASKLETS=16")
	add_ldflags("-DNR_TASKLETS=16")


target("device")
	set_toolchains("upmem-clang")
    set_kind("binary")
    add_files("output/device.c")

target("host")
	set_kind("binary")
	add_files("output/host.c")
	add_files("output/main.c")
	add_includedirs("/usr/local/upmem/include/dpu")
	add_linkdirs("/usr/local/upmem/lib")
	add_links("dpu")
